# Ligne pour le pourcentage graphique
UserParameter=srv1.cpu.percent,snmpwalk -v 2c -c public 192.168.40.1 .1.3.6.1.2.1.25.3.3.1.2 | head -n 1 | awk '{print $NF}'

# Ligne pour l'êtat
UserParameter=srv1.cpu.status,snmpwalk -v 2c -c public 192.168.40.1 .1.3.6.1.2.1.25.3.2.1.5 | head -n 1 | awk '{print $NF}'

# Espace total du disque dur
UserParameter=srv1.disk.total,snmpget -v 2c -c public -Ov 192.168.40.1 .1.3.6.1.2.1.25.2.3.1.5.1 .1.3.6.1.2.1.25.2.3.1.4.1 | awk '{print $2}' | xargs echo | awk '{print $1 * $2}'

# Espace utilisé du disque dur
UserParameter=srv1.disk.used,snmpget -v 2c -c public -Ov 192.168.40.1 .1.3.6.1.2.1.25.2.3.1.6.1 .1.3.6.1.2.1.25.2.3.1.4.1 | awk '{print $2}' | xargs echo | awk '{print $1 * $2}'

# Sauvegarde

# État du service de sauvegarde (VSS) via SNMP
UserParameter=srv1.backup.status,snmpwalk -v 2c -c public 192.168.40.1 .1.3.6.1.2.1.25.4.2.1.2 | grep -ci "vssvc.exe"
