UserParameter=ups.load,upsc eaton@localhost ups.load 2>/dev/null | grep -v "Init"
UserParameter=ups.battery.charge,upsc eaton@localhost battery.charge 2>/dev/null | grep -v "Init"
UserParameter=ups.runtime,upsc eaton@localhost battery.runtime 2>/dev/null | grep -v "Init"
UserParameter=ups.status,upsc eaton@localhost ups.status 2>/dev/null | grep -v "Init"
